const claintSay = [
    {   id:1,   
        topTitle: " Willing to accommodate nonprofit budgets, Cubix brought their robust experience to the project. They checked in consistently, and were communicative, easy to reach, and responsive. The Android app shows over 500 downloads to date. ",
        mainTitle: "Melissa Steward, VP of Marketing",
        subtitle: 'National Fatherhood Initiative',
        companyLogo:'/img/revi_3.png',
        ratingNumber: 4.54,
        reviesNumbr : 6,
    },
    {   id:2,
        topTitle: "Thank you again for the successful launch of the 3M and Converse applications. Your dedication, hard-work, flexibility, patience and professionalism is recognized and appreciated. I would recommend Social Cubix to any company wishing to create their application!",
        mainTitle: "Michael Guzman, Director",
        subtitle: 'Sapient',
        companyLogo:'/img/revi_4.png',
        ratingNumber: 4.7,
        reviesNumbr : 3,
    },
    {   id:3,
        topTitle: " I wanted to make sure everyone on your end knew how pleased we have been with this process. The product 100% looks great. Thank You",
        mainTitle: "Ryan Quinn",
        subtitle: 'National Fire Protection Association',
        companyLogo:'/img/revi_1.png',
        ratingNumber: 4.9,
        reviesNumbr : 17,
    },
    {   id:4,
        topTitle: "I found Cubix provided the highest quality product, and as it was our first experience – that is exceptional for an agency to get it right first time. ",
        mainTitle: "Andrew Wills, UX Lead",
        subtitle: 'Microwave Media',
        companyLogo:'/img/app-futura1.png',
        ratingNumber: 4.7,
        reviesNumbr : 3,
    },
];

export default claintSay;